from functools import lru_cache
from pathlib import Path

from pydantic_settings import BaseSettings, SettingsConfigDict

# The static weekly-outlook benchmark ships inside the package so it is present in
# dev and baked into the Docker image (which copies the `cloudy` package). It is a
# committed artifact regenerated by `cloudy backtest`, not live data.
_BUNDLED_SCORECARD = Path(__file__).resolve().parent / "predictions" / "backtest_scores.json"
# The static spatial benchmark (GBM vs kNN evidence) ships the same way: committed in
# the package, regenerated by `cloudy spatial-backtest`. Not served live — it backs the
# deck's spatial-results slide.
_BUNDLED_SPATIAL_SCORECARD = (
    Path(__file__).resolve().parent / "predictions" / "spatial_backtest.json"
)


class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_file=".env", extra="ignore")

    # Defaults match docker-compose.yml and a cwd of backend/ (how all entry
    # points run); production overrides via env.
    database_url: str = "postgresql+psycopg://cloudy:cloudy@localhost:5432/cloudy"
    log_level: str = "INFO"
    raw_data_dir: str = "../data/raw"
    api_port: int = 8400  # frontend/vite.config.ts proxy target must match
    api_docs: bool = True  # /docs, /redoc, /openapi.json; set false to 404 them
    # Browser origins allowed to call the API (comma-separated). Dev keeps this
    # limited to the Vite app origin; production overrides it with the Cloudflare
    # Pages origin only (e.g. https://cloudy-web.pages.dev).
    cors_allow_origins: str = "http://localhost:5273,http://127.0.0.1:5273"
    geocoder: str = "photon"  # or "nominatim" (on-submit only; its policy bans autocomplete)
    cache_backend: str = "memory"  # process-local; switch to a shared backend when >1 server
    # Where `cloudy backtest` writes the static weekly-outlook benchmark the
    # /predictions/backtest endpoint serves. A computed-once artifact, not live
    # data — committed in the package and regenerated by re-running the eval.
    predictions_scorecard_path: str = str(_BUNDLED_SCORECARD)
    # Where `cloudy spatial-backtest` writes the spatial GBM-vs-kNN benchmark. A
    # computed-once artifact committed in the package, regenerated by re-running the eval.
    spatial_scorecard_path: str = str(_BUNDLED_SPATIAL_SCORECARD)


@lru_cache
def get_settings() -> Settings:
    return Settings()
