from functools import lru_cache

from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_file=".env", extra="ignore")

    # Defaults match docker-compose.yml and a cwd of backend/ (how all entry
    # points run); production overrides via env.
    database_url: str = "postgresql+psycopg://cloudy:cloudy@localhost:5432/cloudy"
    log_level: str = "INFO"
    raw_data_dir: str = "../data/raw"
    api_port: int = 8400  # frontend/vite.config.ts proxy target must match
    api_docs: bool = True  # /docs, /redoc, /openapi.json; set false to 404 them
    # Browser origins allowed to call the API (comma-separated). Dev keeps this
    # limited to the Vite app origin; production overrides it with the Cloudflare
    # Pages origin only (e.g. https://cloudy-web.pages.dev).
    cors_allow_origins: str = "http://localhost:5273,http://127.0.0.1:5273"
    geocoder: str = "photon"  # or "nominatim" (on-submit only; its policy bans autocomplete)
    cache_backend: str = "memory"  # process-local; switch to a shared backend when >1 server
    # Where `cloudy backtest` writes the static weekly-outlook benchmark the
    # /predictions/backtest endpoint serves. A computed-once artifact, not live
    # data — under the gitignored data dir, regenerated by re-running the eval.
    predictions_scorecard_path: str = "../data/backtest_scores.json"


@lru_cache
def get_settings() -> Settings:
    return Settings()
