/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/geocode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Geocode */
        get: operations["geocode_api_v1_geocode_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/station": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Station */
        get: operations["station_api_v1_station_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exploration/lightning": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lightning Route */
        get: operations["lightning_route_api_v1_exploration_lightning_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exploration/cloud": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cloud Route */
        get: operations["cloud_route_api_v1_exploration_cloud_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/climatology/cloud": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cloud Route */
        get: operations["cloud_route_api_v1_climatology_cloud_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/climatology/lightning": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lightning Route */
        get: operations["lightning_route_api_v1_climatology_lightning_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ClimatologyMeta */
        ClimatologyMeta: {
            /** Sources */
            sources: string[];
            /** Attribution */
            attribution: string;
            /** Generated At */
            generated_at: string;
            /** Year Count */
            year_count: number;
        };
        /** ClimatologyStationMeta */
        ClimatologyStationMeta: {
            /** Station Id */
            station_id: number;
            /** Name */
            name: string;
            /** Distance Km */
            distance_km: number;
        };
        /** CloudClimatologyResponse */
        CloudClimatologyResponse: {
            /**
             * Scope
             * @enum {string}
             */
            scope: "station" | "sweden";
            station: components["schemas"]["ClimatologyStationMeta"] | null;
            /** Station Count */
            station_count: number | null;
            /**
             * Period
             * @enum {string}
             */
            period: "day" | "month" | "year";
            /** Series */
            series: components["schemas"]["CloudNormalPoint"][];
            current_month: components["schemas"]["CloudCurrentMonthExpectation"];
            meta: components["schemas"]["ClimatologyMeta"];
        };
        /**
         * CloudCurrentMonthExpectation
         * @description Live expectation for the month in progress: observed-so-far + tail.
         *
         *     `expected_pct` blends the mean of hours already observed this month with the
         *     month's climatological mean for the days not yet elapsed, weighted by how
         *     much of the month each part covers. `baseline_pct` is the plain all-years
         *     monthly normal — what you'd have guessed with no current observations — so
         *     the UI can show how far this month is running from typical.
         */
        CloudCurrentMonthExpectation: {
            /** Month */
            month: number;
            /** Observed So Far Pct */
            observed_so_far_pct: number | null;
            /** Observed Days */
            observed_days: number;
            /** Climatology Tail Pct */
            climatology_tail_pct: number | null;
            /** Expected Pct */
            expected_pct: number | null;
            /** Baseline Pct */
            baseline_pct: number | null;
        };
        /**
         * CloudNormalPoint
         * @description The typical cloud cover for one recurring slot, with a spread band.
         *
         *     The percentile triple (p10/p50/p90) is what turns a flat average into an
         *     honest expectation: a place can average 60% cloud either by being reliably
         *     grey or by swinging between clear and overcast, and only the band shows that.
         *     Counts are carried so a thin slot can't masquerade as a confident one.
         */
        CloudNormalPoint: {
            /** Period */
            period: string;
            /** Mean Cloud Pct */
            mean_cloud_pct: number | null;
            /** P10 Cloud Pct */
            p10_cloud_pct: number | null;
            /** P50 Cloud Pct */
            p50_cloud_pct: number | null;
            /** P90 Cloud Pct */
            p90_cloud_pct: number | null;
            /** Clear Pct */
            clear_pct: number | null;
            /** Partial Pct */
            partial_pct: number | null;
            /** Overcast Pct */
            overcast_pct: number | null;
            /** Observed Count */
            observed_count: number;
            /** Year Count */
            year_count: number;
        };
        /** CloudPeriod */
        CloudPeriod: {
            /** Period */
            period: string;
            /** Bucket Start */
            bucket_start: string;
            /** Bucket End */
            bucket_end: string;
            /** Mean Cloud Pct */
            mean_cloud_pct: number | null;
            /** Min Cloud Pct */
            min_cloud_pct: number | null;
            /** Max Cloud Pct */
            max_cloud_pct: number | null;
            /** P05 Cloud Pct */
            p05_cloud_pct: number | null;
            /** P50 Cloud Pct */
            p50_cloud_pct: number | null;
            /** P95 Cloud Pct */
            p95_cloud_pct: number | null;
            /** Observed Count */
            observed_count: number;
            /** Expected Count */
            expected_count: number;
            /** Missing Count */
            missing_count: number;
        };
        /** CloudResponseMeta */
        CloudResponseMeta: {
            /** From */
            from: string;
            /** To */
            to: string;
            /** Coverage Fraction */
            coverage_fraction: number;
            /** Scope */
            scope: string;
            /** Station Count */
            station_count: number | null;
            /** Sources */
            sources: string[];
            /** Attribution */
            attribution: string;
            /** Generated At */
            generated_at: string;
            /** Total Matched */
            total_matched: number;
            /** Returned */
            returned: number;
            /** Requested Aggregation */
            requested_aggregation: string;
            /** Resolved Resolution */
            resolved_resolution: string;
            /** Mode */
            mode: string;
            /** Representation */
            representation: string;
            /** Target Points */
            target_points: number;
            /** Point Count */
            point_count: number;
            /** Is Complete */
            is_complete: boolean;
        };
        /** CloudSeriesResponse */
        CloudSeriesResponse: {
            /**
             * Aggregation
             * @enum {string}
             */
            aggregation: "auto" | "raw" | "hour" | "6h" | "day" | "week" | "month" | "year";
            /**
             * Resolved Resolution
             * @enum {string}
             */
            resolved_resolution: "raw" | "hour" | "6h" | "day" | "week" | "month" | "year";
            station: components["schemas"]["CloudStationMeta"] | null;
            /** Series */
            series: components["schemas"]["CloudPeriod"][];
            meta: components["schemas"]["CloudResponseMeta"];
        };
        /** CloudStationMeta */
        CloudStationMeta: {
            /** Station Id */
            station_id: number;
            /** Name */
            name: string;
            /** Distance Km */
            distance_km: number;
        };
        /** GeocodeCandidate */
        GeocodeCandidate: {
            /** Label */
            label: string;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Provider */
            provider: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /**
             * Db
             * @enum {string}
             */
            db: "up" | "down";
            /** Version */
            version: string;
        };
        /** LightningClimatologyResponse */
        LightningClimatologyResponse: {
            /**
             * Scope
             * @enum {string}
             */
            scope: "radius" | "sweden";
            /** Lat */
            lat: number | null;
            /** Lon */
            lon: number | null;
            /** Radius Km */
            radius_km: number | null;
            /**
             * Period
             * @enum {string}
             */
            period: "day" | "month" | "year";
            /** Series */
            series: components["schemas"]["LightningNormalPoint"][];
            current_month: components["schemas"]["LightningCurrentMonthExpectation"];
            meta: components["schemas"]["ClimatologyMeta"];
        };
        /**
         * LightningCurrentMonthExpectation
         * @description Live lightning expectation for the month in progress.
         *
         *     Lightning days are additive (a count, not an average), so the blend is a sum:
         *     the days already observed this month plus the climatological expectation for
         *     the days still to come. `baseline_days` is the plain monthly normal.
         */
        LightningCurrentMonthExpectation: {
            /** Month */
            month: number;
            /** Observed Lightning Days */
            observed_lightning_days: number;
            /** Observed Days */
            observed_days: number;
            /** Climatology Tail Days */
            climatology_tail_days: number | null;
            /** Expected Lightning Days */
            expected_lightning_days: number | null;
            /** Baseline Days */
            baseline_days: number | null;
        };
        /**
         * LightningNormalPoint
         * @description The typical lightning activity for one recurring slot within a radius.
         *
         *     `strike_day_probability` is the headline: the chance that any given day in
         *     this slot sees at least one discharge nearby — the same notion as SMHI's
         *     thunder-day maps. `expected_lightning_days` is that probability expressed as
         *     days-per-occurrence of the slot (e.g. per July), and `mean_count` is the raw
         *     discharge volume for callers who want intensity rather than incidence.
         */
        LightningNormalPoint: {
            /** Period */
            period: string;
            /** Strike Day Probability */
            strike_day_probability: number | null;
            /** Expected Lightning Days */
            expected_lightning_days: number | null;
            /** Mean Count */
            mean_count: number | null;
            /** Year Count */
            year_count: number;
        };
        /** LightningPeriod */
        LightningPeriod: {
            /** Period */
            period: string;
            /** Bucket Start */
            bucket_start: string;
            /** Bucket End */
            bucket_end: string;
            /** Cg Count */
            cg_count: number;
            /** All Count */
            all_count: number;
            /** Lightning Days */
            lightning_days: number;
            /** Max Abs Peak Ka */
            max_abs_peak_ka: number;
            /** Strongest Event Time */
            strongest_event_time: string | null;
        };
        /** LightningSeriesResponse */
        LightningSeriesResponse: {
            /**
             * Format
             * @constant
             */
            format: "series";
            /**
             * Aggregation
             * @enum {string}
             */
            aggregation: "auto" | "raw" | "hour" | "6h" | "day" | "week" | "month" | "year";
            /**
             * Resolved Resolution
             * @enum {string}
             */
            resolved_resolution: "raw" | "hour" | "6h" | "day" | "week" | "month" | "year";
            /** Spatial */
            spatial: components["schemas"]["SpatialMetaSweden"] | components["schemas"]["SpatialMetaBbox"] | components["schemas"]["SpatialMetaRadius"];
            /** Series */
            series: components["schemas"]["LightningPeriod"][];
            meta: components["schemas"]["SeriesResponseMeta"];
        };
        /** LightningStrokesResponse */
        LightningStrokesResponse: {
            /**
             * Format
             * @constant
             */
            format: "strokes";
            /** Columns */
            columns: ("lon" | "lat" | "peak_ka" | "cg" | "ts")[];
            /** Rows */
            rows: (number)[][];
            /** Spatial */
            spatial: components["schemas"]["SpatialMetaSweden"] | components["schemas"]["SpatialMetaBbox"] | components["schemas"]["SpatialMetaRadius"];
            meta: components["schemas"]["StrokesResponseMeta"];
        };
        /** SeriesResponseMeta */
        SeriesResponseMeta: {
            /** From */
            from: string;
            /** To */
            to: string;
            /** Sources */
            sources: string[];
            /** Attribution */
            attribution: string;
            /** Generated At */
            generated_at: string;
            /** Total Matched */
            total_matched: number;
            /** Returned */
            returned: number;
            /** Requested Aggregation */
            requested_aggregation: string;
            /** Resolved Resolution */
            resolved_resolution: string;
            /** Mode */
            mode: string;
            /** Representation */
            representation: string;
            /** Target Points */
            target_points: number;
            /** Point Count */
            point_count: number;
            /** Is Complete */
            is_complete: boolean;
        };
        /** SpatialMetaBbox */
        SpatialMetaBbox: {
            /**
             * Mode
             * @constant
             */
            mode: "bbox";
            /** Bbox */
            bbox: number[];
        };
        /** SpatialMetaRadius */
        SpatialMetaRadius: {
            /**
             * Mode
             * @constant
             */
            mode: "radius";
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Radius Km */
            radius_km: number;
        };
        /** SpatialMetaSweden */
        SpatialMetaSweden: {
            /**
             * Mode
             * @constant
             */
            mode: "sweden";
            /** Bbox */
            bbox: number[];
        };
        /** StationResponse */
        StationResponse: {
            /** Station Id */
            station_id: number;
            /** Name */
            name: string;
            /** Distance Km */
            distance_km: number;
        };
        /** StrokesResponseMeta */
        StrokesResponseMeta: {
            /** From */
            from: string;
            /** To */
            to: string;
            /** Sources */
            sources: string[];
            /** Attribution */
            attribution: string;
            /** Generated At */
            generated_at: string;
            /** Total Matched */
            total_matched: number;
            /** Returned */
            returned: number;
            /** Downsampled */
            downsampled: boolean;
            /** Stride */
            stride: number | null;
            /** Sample Method */
            sample_method: string | null;
            /** Dropped Count */
            dropped_count: number;
            /** Representation */
            representation: string;
            /** Is Complete */
            is_complete: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    geocode_api_v1_geocode_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeocodeCandidate"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    station_api_v1_station_get: {
        parameters: {
            query: {
                lat: number;
                lon: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lightning_route_api_v1_exploration_lightning_get: {
        parameters: {
            query?: {
                from?: string;
                to?: string | null;
                lat?: number | null;
                lon?: number | null;
                radius_km?: number | null;
                bbox?: string | null;
                format?: "series" | "strokes";
                aggregation?: "auto" | "raw" | "hour" | "6h" | "day" | "week" | "month" | "year";
                width_px?: number | null;
                max_points?: number | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LightningSeriesResponse"] | components["schemas"]["LightningStrokesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cloud_route_api_v1_exploration_cloud_get: {
        parameters: {
            query?: {
                lat?: number | null;
                lon?: number | null;
                from?: string;
                to?: string | null;
                aggregation?: "auto" | "raw" | "hour" | "6h" | "day" | "week" | "month" | "year";
                width_px?: number | null;
                max_points?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CloudSeriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cloud_route_api_v1_climatology_cloud_get: {
        parameters: {
            query?: {
                lat?: number | null;
                lon?: number | null;
                period?: "day" | "month" | "year";
                radius_km?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CloudClimatologyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lightning_route_api_v1_climatology_lightning_get: {
        parameters: {
            query?: {
                lat?: number | null;
                lon?: number | null;
                period?: "day" | "month" | "year";
                radius_km?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LightningClimatologyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
