/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/geocode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Geocode */
        get: operations["geocode_api_v1_geocode_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lightning": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lightning Route */
        get: operations["lightning_route_api_v1_lightning_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cloud": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cloud Route */
        get: operations["cloud_route_api_v1_cloud_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/station": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Station */
        get: operations["station_api_v1_station_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CloudPeriod */
        CloudPeriod: {
            /** Period */
            period: string;
            /** Bucket Start */
            bucket_start: string;
            /** Bucket End */
            bucket_end: string;
            /** Mean Cloud Pct */
            mean_cloud_pct: number | null;
            /** Min Cloud Pct */
            min_cloud_pct: number | null;
            /** Max Cloud Pct */
            max_cloud_pct: number | null;
            /** P05 Cloud Pct */
            p05_cloud_pct: number | null;
            /** P50 Cloud Pct */
            p50_cloud_pct: number | null;
            /** P95 Cloud Pct */
            p95_cloud_pct: number | null;
            /** Observed Count */
            observed_count: number;
            /** Expected Count */
            expected_count: number;
            /** Missing Count */
            missing_count: number;
        };
        /** CloudResponseMeta */
        CloudResponseMeta: {
            /** From */
            from: string;
            /** To */
            to: string;
            /** Coverage Fraction */
            coverage_fraction: number;
            /** Scope */
            scope: string;
            /** Station Count */
            station_count: number | null;
            /** Sources */
            sources: string[];
            /** Attribution */
            attribution: string;
            /** Generated At */
            generated_at: string;
            /** Total Matched */
            total_matched: number;
            /** Returned */
            returned: number;
            /** Requested Aggregation */
            requested_aggregation: string;
            /** Resolved Resolution */
            resolved_resolution: string;
            /** Mode */
            mode: string;
            /** Representation */
            representation: string;
            /** Target Points */
            target_points: number;
            /** Point Count */
            point_count: number;
            /** Is Complete */
            is_complete: boolean;
        };
        /** CloudSeriesResponse */
        CloudSeriesResponse: {
            /**
             * Aggregation
             * @enum {string}
             */
            aggregation: "auto" | "raw" | "hour" | "6h" | "day" | "week" | "month" | "year";
            /**
             * Resolved Resolution
             * @enum {string}
             */
            resolved_resolution: "raw" | "hour" | "6h" | "day" | "week" | "month" | "year";
            station: components["schemas"]["CloudStationMeta"] | null;
            /** Series */
            series: components["schemas"]["CloudPeriod"][];
            meta: components["schemas"]["CloudResponseMeta"];
        };
        /** CloudStationMeta */
        CloudStationMeta: {
            /** Station Id */
            station_id: number;
            /** Name */
            name: string;
            /** Distance Km */
            distance_km: number;
        };
        /** GeocodeCandidate */
        GeocodeCandidate: {
            /** Label */
            label: string;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Provider */
            provider: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /**
             * Db
             * @enum {string}
             */
            db: "up" | "down";
            /** Version */
            version: string;
        };
        /** LightningPeriod */
        LightningPeriod: {
            /** Period */
            period: string;
            /** Bucket Start */
            bucket_start: string;
            /** Bucket End */
            bucket_end: string;
            /** Cg Count */
            cg_count: number;
            /** All Count */
            all_count: number;
            /** Lightning Days */
            lightning_days: number;
            /** Max Abs Peak Ka */
            max_abs_peak_ka: number;
            /** Strongest Event Time */
            strongest_event_time: string | null;
        };
        /** LightningSeriesResponse */
        LightningSeriesResponse: {
            /**
             * Format
             * @constant
             */
            format: "series";
            /**
             * Aggregation
             * @enum {string}
             */
            aggregation: "auto" | "raw" | "hour" | "6h" | "day" | "week" | "month" | "year";
            /**
             * Resolved Resolution
             * @enum {string}
             */
            resolved_resolution: "raw" | "hour" | "6h" | "day" | "week" | "month" | "year";
            /** Spatial */
            spatial: components["schemas"]["SpatialMetaSweden"] | components["schemas"]["SpatialMetaBbox"] | components["schemas"]["SpatialMetaRadius"];
            /** Series */
            series: components["schemas"]["LightningPeriod"][];
            meta: components["schemas"]["SeriesResponseMeta"];
        };
        /** LightningStrokesResponse */
        LightningStrokesResponse: {
            /**
             * Format
             * @constant
             */
            format: "strokes";
            /** Columns */
            columns: ("lon" | "lat" | "peak_ka" | "cg" | "ts")[];
            /** Rows */
            rows: (number)[][];
            /** Spatial */
            spatial: components["schemas"]["SpatialMetaSweden"] | components["schemas"]["SpatialMetaBbox"] | components["schemas"]["SpatialMetaRadius"];
            meta: components["schemas"]["StrokesResponseMeta"];
        };
        /** SeriesResponseMeta */
        SeriesResponseMeta: {
            /** From */
            from: string;
            /** To */
            to: string;
            /** Sources */
            sources: string[];
            /** Attribution */
            attribution: string;
            /** Generated At */
            generated_at: string;
            /** Total Matched */
            total_matched: number;
            /** Returned */
            returned: number;
            /** Requested Aggregation */
            requested_aggregation: string;
            /** Resolved Resolution */
            resolved_resolution: string;
            /** Mode */
            mode: string;
            /** Representation */
            representation: string;
            /** Target Points */
            target_points: number;
            /** Point Count */
            point_count: number;
            /** Is Complete */
            is_complete: boolean;
        };
        /** SpatialMetaBbox */
        SpatialMetaBbox: {
            /**
             * Mode
             * @constant
             */
            mode: "bbox";
            /** Bbox */
            bbox: number[];
        };
        /** SpatialMetaRadius */
        SpatialMetaRadius: {
            /**
             * Mode
             * @constant
             */
            mode: "radius";
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Radius Km */
            radius_km: number;
        };
        /** SpatialMetaSweden */
        SpatialMetaSweden: {
            /**
             * Mode
             * @constant
             */
            mode: "sweden";
            /** Bbox */
            bbox: number[];
        };
        /** StationResponse */
        StationResponse: {
            /** Station Id */
            station_id: number;
            /** Name */
            name: string;
            /** Distance Km */
            distance_km: number;
        };
        /** StrokesResponseMeta */
        StrokesResponseMeta: {
            /** From */
            from: string;
            /** To */
            to: string;
            /** Sources */
            sources: string[];
            /** Attribution */
            attribution: string;
            /** Generated At */
            generated_at: string;
            /** Total Matched */
            total_matched: number;
            /** Returned */
            returned: number;
            /** Downsampled */
            downsampled: boolean;
            /** Stride */
            stride: number | null;
            /** Sample Method */
            sample_method: string | null;
            /** Dropped Count */
            dropped_count: number;
            /** Representation */
            representation: string;
            /** Is Complete */
            is_complete: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    geocode_api_v1_geocode_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeocodeCandidate"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lightning_route_api_v1_lightning_get: {
        parameters: {
            query?: {
                from?: string;
                to?: string | null;
                lat?: number | null;
                lon?: number | null;
                radius_km?: number | null;
                bbox?: string | null;
                format?: "series" | "strokes";
                aggregation?: "auto" | "raw" | "hour" | "6h" | "day" | "week" | "month" | "year";
                width_px?: number | null;
                max_points?: number | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LightningSeriesResponse"] | components["schemas"]["LightningStrokesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cloud_route_api_v1_cloud_get: {
        parameters: {
            query?: {
                lat?: number | null;
                lon?: number | null;
                from?: string;
                to?: string | null;
                aggregation?: "auto" | "raw" | "hour" | "6h" | "day" | "week" | "month" | "year";
                width_px?: number | null;
                max_points?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CloudSeriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    station_api_v1_station_get: {
        parameters: {
            query: {
                lat: number;
                lon: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
